### ISSUE TITLE
安装成功但无法启动

### ISSUE THREAD

**Issue by bigzero61** [JezaChen/MendeleyDesktop-For-Ubuntu-22.04#1]
安装很成功无任何报错，但点击应用图标时无任何反应

**Comment by JezaChen** [comment]
麻烦在终端上直接使用命令`mendeleydesktop`打开Mendeley，看看有没有输出报错信息~

**Comment by bigzero61** [comment]
嗯后来找到原因发现是python软链接无效 重新链接python3即可

Chen Jianzhang ***@***.***> 于2022年12月9日周五 12:23写道：

**Comment by bigzero61** [comment]
嗯后来找到原因发现是python软链接无效 重新链接python3即可

**Comment by Huang-CL** [comment]
Encountered the same problem on Ubuntu 22.04.  Can only launch it through the terminal.  The desktop shortcut is not responsive.  Adding it to the startup applications also doesn't help.
The problem is solved after installing the package `python-is-python3`.
